services:
  db:
    image: postgres:16-alpine
    container_name: db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  django:
    build: ./django
    container_name: django
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    volumes:
      - ./django:/app
    expose:
      - "8000"
    command: ["/app/entrypoint.sh"]

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
