apiVersion: v2
name: django-app
description: Django application for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 16.7.15
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled